### ISSUE TITLE
Question - not an issue

### ISSUE THREAD

**Issue by dstroot** [mjhea0/node-stripe-charge#5]
I like your code structure and organization.  However I don't understand the reason behind creating the `bin` directory under `server` and creating the `www` file.  Can you explain why?  Thanks in advance!

I can see this is where we actually start listening (basically what it does) - I just don't know why it's organized this way.

**Comment by mjhea0** [comment]
Thanks. I used the [express generator](https://www.npmjs.com/package/express-generator) to bootstrap the structure. They use the *bin/www* structure.

**Comment by dstroot** [comment]
Ok thanks
