### ISSUE TITLE
What is the mongod database location?

### ISSUE THREAD

**Issue by drewrwilson** [mjhea0/node-stripe-charge#6]
when I started mongod, I got this error:

`ERROR: dbpath (/data/db) does not exist. `
` Create this directory or give existing directory in --dbpath. `
` See http://dochub.mongodb.org/core/startingandstoppingmongo `

What is the right way to start this? I can create a directory and specify that with the `--dbpath` flag, but then I don't get the db seeded with the admin login.

I appreciate any help! :)

**Comment by mjhea0** [comment]
You need to install a data directory -> http://docs.mongodb.org/manual/tutorial/install-mongodb-on-os-x/?_ga=1.229193244.1079271488.1425946980#create-the-data-directory

**Comment by drewrwilson** [comment]
Thank you!
